config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :user_tasks, only: [ :index ] do
    put 'mark_as_done_user_task', to: 'user_tasks#mark_as_done', as: :mark_as_done_user_tasks
  end
  resources :plants, only: [ :index, :show ] do

    resources :garden_plants, only: [ :create ]
    resources :tasks, only: [ :index, :show ]
  end

  resources :garden_plants, only: [ :destroy ]

  resources :gardens, only: [:show, :create ]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :garden_plants
end

app/models/garden_plant.rb
class GardenPlant < ApplicationRecord
  belongs_to :garden
  belongs_to :plant
  after_destroy :destroy_user_tasks

  private

  def destroy_user_tasks
    self.plant.tasks.each do |task|
      UserTask.where(user: self.garden.user, task: task).destroy_all
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :tasks
  has_many :garden_plants, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :plant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  has_one :garden
  after_create :create_garden

  private

  def create_garden
    Garden.create!(user: self)
  end
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/garden_plants_controller.rb
class GardenPlantsController < ApplicationController
  def create
    garden_plant = GardenPlant.new()
    garden_plant.plant = Plant.find(params[:plant_id])
    garden_plant.garden = current_user.garden

    if garden_plant.save
      garden_plant.plant.tasks.each do |task|
        UserTask.create!(user_id: current_user.id, task_id: task.id)
      end
      redirect_to garden_path(current_user.garden)
    end
  end

  def destroy
    @garden_plant = GardenPlant.find(params[:id])
    @garden_plant.destroy
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

  def show
    @garden = Garden.find(params[:id])
    @garden_plants = @garden.garden_plants
    @number_of_plots = 20 - @garden_plants.count
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :index, :show ]

  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @vegeplants = Plant.where(category: "vegetable")
    @fruitplants = Plant.where(category: "fruit")
  end

  def show
    @plant = Plant.find(params[:id])
    @months = %w[jan feb mar apr may jun jul aug sep oct nov dec]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show

  end

  def index

  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController

  def index
    @user_tasks_by_plant = UserTask.where(validated: false)
      .where(user: current_user)
      .joins(:task)
      .group_by { |ut| ut.task.plant }
  end

  def mark_as_done
    @task_done = UserTask.find(params[:user_task_id])
    @task_done.validated = true
    @task_done.save

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_tasks_count
    UserTask.where(validated: false).where(user: current_user).count
  end
end

app/views/garden_plants/create.html.erb
<h1>GardenPlants#create</h1>
<p>Find me in app/views/garden_plants/create.html.erb</p>

app/views/garden_plants/destroy.js.erb
document.querySelector("[data-garden_plant-id='<%= @garden_plant.id %>']").remove();

var task_counter = document.querySelector("#task_counter_btn");
task_counter.innerText = `Check your tasks (${<%= user_tasks_count %>})`;

// update navbae
document.getElementById('task_counter').innerText = `My Tasks (${<%= user_tasks_count %>})`;

app/views/gardens/create.html.erb
<h1>Gardens#create</h1>
<p>Find me in app/views/gardens/create.html.erb</p>

app/views/gardens/show.html.erb
  <div class="grass">

  <h1> <%= current_user.username.capitalize %>'s Garden <%= image_tag "maybelogo.png", alt: "carrot", width: 100 %></h1>


  <div class="buttton">
    <%= link_to user_tasks_path, {id: 'task_counter_btn', class: "obbtn"} do %>
               Check your tasks (<%= user_tasks_count %>)
        <% end %>
    <%= link_to plants_path, {class: "obbtn"} do %>
               Choose another plant
        <% end %>
  </div>

<div class="garden">
  <% @garden_plants.each do |garden_plant| %>
    <div class="plot">
      <div class="logo" style="background-image: url('<%= cl_image_path garden_plant.plant.logo_url %>')" data-garden_plant-id="<%= garden_plant.id %>">
        <%= link_to garden_plant, method: :delete, remote: true do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  <% end %>

  <% @number_of_plots.times do  %>
    <div class="plot"></div>
  <% end %>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Let's plant" %></title>
    <meta name="Keep track of your garden online!" content="Keep track of your garden online!" >
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Karla|Montserrat&display=swap" rel="stylesheet">
    <title>Let's Plant</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
     <%= favicon_link_tag asset_path('favicon.png') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="layoutcontainer">
      <%= yield %>
     <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="containerhome">
    <div class="inner-container">
      <div class="inner-intro">
        <h2 class="focus-in-expand"> Learn how to garden!</h2>
        <p> Keep track of your garden online</p>
        <div class="action">
             <%= link_to plants_path, {class: "obbtn"} do %>
               Start to plant!
             <% end %>
        </div>
      </div>
    </div>



  <div id="carouselSlides" class="carousel" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(20).logo_url%>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(13).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(14).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(5).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(18).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(17).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(15).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(11).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(6).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(9).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(10).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(11).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(12).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(13).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(14).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(15).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(16).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(17).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(18).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(19).logo_url %>' width="600" style = "padding: 100px;">
      </div>
      <div class="carousel-item">
        <img class="d-flex bounce-in-top" src='<%= cl_image_path Plant.find(20).logo_url %>' width="600" style = "padding: 100px;">
      </div>
    </div>
  </div>

</div>

app/views/plants/index.html.erb
  <div class="container-index-plants">
    <div class="vegetables">
      <div><h2>Vegetables:</h2></div>
      <div class="cards-index">
        <% @vegeplants.each do |plant| %>
          <%= link_to plant_path(plant), {class: "card-over"} do %>
            <div class="card-category-index fade-in" style="background-image: url('<%= cl_image_path plant.logo_url %>')">
              <%= plant.name %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="fruits">
      <div><h2>Fruits:</h2></div>
      <div class="cards-index">
        <% @fruitplants.each do |plant| %>
          <%= link_to plant_path(plant), {class: "card-over"} do %>
            <div class="card-category-index fade-in" style="background-image: url('<%= cl_image_path plant.logo_url %>')">
              <%= plant.name %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>


  </div>

app/views/plants/show.html.erb
  <div class="title_show">
   <h2><%= @plant.name %></h2>
  </div>
    <div class="container3">
      <div class= "information_plant">
        <p><strong>Best to plant in :</strong>
          <table>
            <tr>
             <% @months.each do |month| %>
                <td class="<%= 'colored' if @plant.plant_date[month] %>"><%= month %></td>
              <% end %>
            </tr>
          </table>
        </p>
        <p><strong>Harvest in :</strong>
          <table>
            <tr>
             <% @months.each do |month| %>
                <td class="<%= 'colored' if @plant.harvest_date[month] %>"><%= month %></td>
              <% end %>
            </tr>
          </table>
        </p>
        <p><strong>Difficulty :</strong>
        </p>
        <% if @plant.difficulty == 1 %>
          <%= image_tag "sproutfull.png", height: '35' %>
          <%= image_tag "sprout.png", height: '35' %>
          <%= image_tag "sprout.png", height: '35' %>
        <% elsif @plant.difficulty == 2 %>
          <%= image_tag "sproutfull.png", height: '35' %>
          <%= image_tag "sproutfull.png", height: '35' %>
          <%= image_tag "sprout.png", height: '35' %>
        <% else %>
          <%= image_tag "sproutfull.png", height: '35' %>
          <%= image_tag "sproutfull.png", height: '35' %>
          <%= image_tag "sproutfull.png", height: '35' %>
        <% end %>
      </div>
      <div class="image_and_button">
        <div class="image_show" style="background-image: url(<%= cl_image_path @plant.logo_url %>)">
        </div>
        <%= link_to plant_garden_plants_path(@plant), method: :post,class: "obtn" do %>
          Add to my personalized garden
        <% end %>
      </div>
    </div>

    <div class="plant_description">
      <p> <strong>General info :</strong></p>
       <p> <%= @plant.description %></p>
       <p> <strong>Sowing information :</strong></p>
        <p><%= @plant.description_details %></p>
        <div class="fun_fact">
       <span>&#x1F62E</span><p>"<%= @plant.fun_fact %>"</p>
       </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
      <a href="#"><i class="fab fa-github-square"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
    © 2019 Let's Plant Inc. <i class="fas fa-carrot"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
<%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "maybelogo.png" %>
  <% end %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Plants", plants_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Garden", garden_path(current_user.garden), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Tasks (#{user_tasks_count})", user_tasks_path, class: "nav-link", id: 'task_counter' %>
      </li>
    <% else %>
    <% end %>
  </ul>
</div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>

app/views/user_tasks/index.html.erb
<div class="main_container">
  <h1>Today To Do list:</h1>


  <div class="tasks_container">


    <% @user_tasks_by_plant.each do |plant, user_tasks| %>

    <div class="task_container">
      <div class="headertask">
        <div class="log" style="background-image: url('<%= cl_image_path plant.logo_url %>')">
        </div>
        <h2><%= plant.name %></h2>

      </div>


      <ul>

        <% user_tasks.each do |user_task| %>

          <div class="task_plant" data-user-task-id="<%= user_task.id %>">
            <li>
              <p><%= user_task.task.description %></p>

              <%= link_to user_task_mark_as_done_user_tasks_path(user_task), class: "ubtn", method: :put, remote: true, id: "#{user_task.id}" do %>
                  <div class="check">done</div>

              <% end %>
            </li>
          </div>
          <% end %>
        </ul>
      </div>
    <% end %>

  </div>
</div>

app/views/user_tasks/mark_as_done.js.erb
document.querySelector("[data-user-task-id='<%= @task_done.id %>']").style.opacity = '0';
setTimeout(function(){document.querySelector("[data-user-task-id='<%= @task_done.id %>']").remove();}, 1000);

document.getElementById('task_counter').innerText = `My Tasks (${<%= user_tasks_count %>})`;